language: node_js
cache: yarn
node_js:
  - '6'
  - '8'
  - '10'
env:
  - STYLELINT_VERSION=latest
  - STYLELINT_VERSION=9.5.0
before_script:
  - if [[ $STYLELINT_VERSION != "latest" ]]; then
    yarn upgrade "stylelint@$STYLELINT_VERSION";
    fi
